### ISSUE TITLE
Comparison with RUM ?

### ISSUE THREAD

**Issue by hansgru** [levand/quiescent#41]
Hi,

It's very useful that there's a comparison with ```om``` and ```reagent```.
Please add a comparison with ```rum``` too: https://github.com/tonsky/rum

Thank you.

**Comment by bzz** [comment]
It would be quite valuable if somebody could contribute that.

RUM
> Minimal React wrapper for ClojureScript. Decomplected, extensible, simple

[Intro](https://vimeo.com/122316380)
Mentions [Quiescent](https://github.com/tonsky/rum#acknowledgements) as an inspiration

Quiescent
> A lightweight ClojureScript abstraction over ReactJS

[Intro by author](https://www.youtube.com/watch?v=oRmj3IUkRVk&list=PLZdCLR02grLrKAOj8FJ1GGmNM5l7Okz0a)

It looks like both have about the same number of stars\commits\contributors\traction and both are only compared with Om and Reagent.

**Comment by levand** [comment]
Quiescent doesn't have a comparison with Rum because it predates Rum by a good bit, Rum did not inform its design.

The short answer to "what are the differences?" is that Rum is more abstract and hooks into React at a lower level, allowing you to extend behavior in different ways. It can do things that look very much like Quiescent, but also different things. It also supports a Hiccup/Sablono HTML syntax by default, which Quiescent does not.

Choosing between it and Quiescent is mostly a matter of taste, based on how opinionated you want to be about Quiescent's model, and whether you like Sablono/Hiccup.

I'm not going to update the official docs to include this comparison because that would imply that I am taking on the perpetual responsibility of comparing/contrasting Quiescent with every new React framework that comes along, and keeping them up to date, which terrifies me :)

**Comment by bzz** [comment]
Thank you very much for you time and clear explanation! Makes perfect sense
