### ISSUE TITLE
benchmarks

### ISSUE THREAD

**Issue by Raynos** [levand/quiescent#9]
It would be nice to see the benchmarks for react & om re-implement in `quiescent` to see how well this approach performs.

**Comment by ivanreese** [comment]
+1

**Comment by levand** [comment]
While I think it would be interesting to see these, they would represent a substantial time investment to do correctly and in a general way. Since I currently have no plans to put a lot of time into this, I'm going to go ahead and close this issue.

If anyone else wants to take it on, PRs or links to benchmark results would be welcome as always.
